




# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledFFkUfH.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.Qt import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(798, 524)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 20, 351, 461))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.status = QWidget(self.frame)
        self.status.setObjectName(u"status")
        self.status.setGeometry(QRect(0, 0, 351, 461))
        self.status.setAutoFillBackground(True)
        self.label = QLabel(self.status)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 71, 31))
        self.label.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.altitude = QLabel(self.status)
        self.altitude.setObjectName(u"altitude")
        self.altitude.setEnabled(True)
        self.altitude.setGeometry(QRect(40, 340, 201, 31))
        self.altitude.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.speed = QLabel(self.status)
        self.speed.setObjectName(u"speed")
        self.speed.setGeometry(QRect(40, 360, 201, 31))
        self.speed.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.location = QLabel(self.status)
        self.location.setObjectName(u"location")
        self.location.setGeometry(QRect(40, 380, 221, 31))
        self.location.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.pressure = QLabel(self.status)
        self.pressure.setObjectName(u"pressure")
        self.pressure.setGeometry(QRect(40, 400, 221, 31))
        self.pressure.setBaseSize(QSize(0, 0))
        self.pressure.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.pressure.setScaledContents(True)
        self.pressure.setWordWrap(False)
        self.pressure.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.listView = QListView(self.status)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(20, 320, 256, 141))
        self.graphicsView = QGraphicsView(self.status)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 30, 121, 81))
        self.graphicsView.setStyleSheet(u"background-image: url(:/newPrefix/Line-Graph.png);")
        self.graphicsView_2 = QGraphicsView(self.status)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(190, 30, 121, 81))
        self.graphicsView_2.setStyleSheet(u"background-image: url(:/newPrefix/Line-Graph.png);")
        self.graphicsView_3 = QGraphicsView(self.status)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(10, 140, 121, 81))
        self.graphicsView_3.setStyleSheet(u"background-image: url(:/newPrefix/Line-Graph.png);")
        self.graphicsView_4 = QGraphicsView(self.status)
        self.graphicsView_4.setObjectName(u"graphicsView_4")
        self.graphicsView_4.setGeometry(QRect(190, 140, 121, 81))
        self.graphicsView_4.setAutoFillBackground(False)
        self.graphicsView_4.setStyleSheet(u"background-image: url(:/newPrefix/Line-Graph.png);")
        brush = QBrush(QColor(85, 255, 255, 255))
        brush.setStyle(Qt.Dense2Pattern)
        self.graphicsView_4.setBackgroundBrush(brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        self.graphicsView_4.setForegroundBrush(brush1)
        self.graphicsView_4.setDragMode(QGraphicsView.NoDrag)
        self.graphicsView_4.setTransformationAnchor(QGraphicsView.NoAnchor)
        self.satalite_num = QLabel(self.status)
        self.satalite_num.setObjectName(u"satalite_num")
        self.satalite_num.setEnabled(True)
        self.satalite_num.setGeometry(QRect(40, 430, 251, 19))
        self.satalite_num.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.listView.raise_()
        self.label.raise_()
        self.altitude.raise_()
        self.speed.raise_()
        self.location.raise_()
        self.pressure.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView_3.raise_()
        self.graphicsView_4.raise_()
        self.satalite_num.raise_()
        self.graphicsView.raise_()
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(370, 340, 421, 141))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.widget_2 = QWidget(self.frame_2)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(0, 0, 411, 141))
        self.widget_2.setAutoFillBackground(True)
        self.fireButton = QPushButton(self.widget_2)
        self.fireButton.setObjectName(u"fireButton")
        self.fireButton.setGeometry(QRect(290, 50, 111, 41))
        self.unlock_Button = QPushButton(self.widget_2)
        self.unlock_Button.setObjectName(u"unlock_Button")
        self.unlock_Button.setGeometry(QRect(140, 100, 141, 31))
        self.checkButton = QPushButton(self.widget_2)
        self.checkButton.setObjectName(u"checkButton")
        self.checkButton.setGeometry(QRect(30, 50, 111, 41))
        self.initiate_Button = QPushButton(self.widget_2)
        self.initiate_Button.setObjectName(u"initiate_Button")
        self.initiate_Button.setGeometry(QRect(160, 40, 111, 41))
        self.listView_2 = QListView(self.widget_2)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(0, 30, 411, 111))
        self.listView_2.raise_()
        self.fireButton.raise_()
        self.unlock_Button.raise_()
        self.checkButton.raise_()
        self.initiate_Button.raise_()
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(370, 20, 421, 341))
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.widget = QWidget(self.frame_3)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 421, 341))
        self.widget.setAutoFillBackground(True)
        self.openGLWidget = QOpenGLWidget(self.widget)
        self.openGLWidget.setObjectName(u"openGLWidget")
        self.openGLWidget.setGeometry(QRect(50, 30, 300, 200))
        self.openGLWidget.setAutoFillBackground(False)
        self.openGLWidget.setStyleSheet(u"background-image: url(:/newPrefix/istockphoto-1317488792-612x612.jpg);")
        self.graphicsView_5 = QGraphicsView(self.widget)
        self.graphicsView_5.setObjectName(u"graphicsView_5")
        self.graphicsView_5.setGeometry(QRect(30, 0, 341, 271))
        self.graphicsView_5.setAutoFillBackground(False)
        self.graphicsView_5.setStyleSheet(u"background-image: url(:/newPrefix/istockphoto-1317488792-612x612.jpg);")
        brush2 = QBrush(QColor(85, 255, 255, 255))
        brush2.setStyle(Qt.Dense2Pattern)
        self.graphicsView_5.setBackgroundBrush(brush2)
        self.graphicsView_5.setForegroundBrush(brush1)
        self.graphicsView_5.setDragMode(QGraphicsView.NoDrag)
        self.graphicsView_5.setTransformationAnchor(QGraphicsView.NoAnchor)
        self.listView_3 = QListView(self.widget)
        self.listView_3.setObjectName(u"listView_3")
        self.listView_3.setGeometry(QRect(30, 270, 341, 61))
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 270, 121, 31))
        self.label_7.setBaseSize(QSize(0, 0))
        self.label_7.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(False)
        self.label_7.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 290, 121, 31))
        self.label_8.setBaseSize(QSize(0, 0))
        self.label_8.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(False)
        self.label_8.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(190, 270, 121, 31))
        self.label_9.setBaseSize(QSize(0, 0))
        self.label_9.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.label_9.setScaledContents(True)
        self.label_9.setWordWrap(False)
        self.label_9.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(190, 290, 161, 31))
        self.label_10.setBaseSize(QSize(0, 0))
        self.label_10.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";")
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(False)
        self.label_10.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.altitude.setText(QCoreApplication.translate("MainWindow", u"Altitude: {altitute}", None))
        self.speed.setText(QCoreApplication.translate("MainWindow", u"Speed: {speed}", None))
        self.location.setText(QCoreApplication.translate("MainWindow", u"Location: {location}", None))
        self.pressure.setText(QCoreApplication.translate("MainWindow", u"Pressure: {pressure}", None))
        self.satalite_num.setText(QCoreApplication.translate("MainWindow", u"Satalites num: {satalites}", None))
        self.fireButton.setText(QCoreApplication.translate("MainWindow", u"Fire Launch", None))
        self.unlock_Button.setText(QCoreApplication.translate("MainWindow", u"Unlock Password", None))
        self.checkButton.setText(QCoreApplication.translate("MainWindow", u"Check System", None))
        self.initiate_Button.setText(QCoreApplication.translate("MainWindow", u"Initiate Launch", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Long: xxxx", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Lat: xxxx", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Speed: xxxx", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Travelled dist: xxxx", None))

    # retranslateUi

